services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    labels:
      service-role: "database"
    networks:
      - app_network

  backend:
    container_name: conduit-backend
    restart: unless-stopped
    image: ghcr.io/${REPOSITORY_OWNER}/conduit-container/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    labels:
      service-role: "backend"
    networks:
      - app_network

  frontend:
    container_name: conduit-frontend
    restart: unless-stopped
    image: ghcr.io/${REPOSITORY_OWNER}/conduit-container/frontend:latest
    ports:
      - "8282:80"
    labels:
      service-role: "frontend"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge